# Generated by Django 5.2.6 on 2025-09-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('embedding', models.JSONField(verbose_name='Embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
