# Generated by Django 5.2.6 on 2025-09-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='brief',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
