# Generated by Django 5.2.6 on 2025-10-12 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_openaisettings_delete_guest_delete_property_and_more'),
        ('knowledge', '0002_knowledgebase_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='core.openaisettings'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Embedding'),
        ),
    ]
