# Generated by Django 5.1.5 on 2025-07-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_property_address_alter_property_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='id_num',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
