# Generated by Django 5.1.5 on 2025-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_guest_id_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
