# Generated by Django 5.2.6 on 2025-10-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guest_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('gpt-5', 'GPT-5'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4.1-mini', 'GPT-4.1 Mini')], default='gpt-4o', max_length=50, verbose_name='Model')),
                ('agent_name', models.CharField(default='agentname', help_text='The display name of the assistant/agent', max_length=100)),
                ('system_context', models.TextField(default='You are a helpful assistant.', help_text='System message for the agent. Can be a long instruction or persona.')),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=1.0)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenAI Setting',
                'verbose_name_plural': 'OpenAI Settings',
            },
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
