# Generated by Django 5.2.6 on 2025-09-10 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('DZ', 'Algeria'), ('BH', 'Bahrain'), ('KM', 'Comoros'), ('DJ', 'Djibouti'), ('EG', 'Egypt'), ('IQ', 'Iraq'), ('JO', 'Jordan'), ('KW', 'Kuwait'), ('LB', 'Lebanon'), ('LY', 'Libya'), ('MR', 'Mauritania'), ('MA', 'Morocco'), ('OM', 'Oman'), ('PS', 'Palestine'), ('QA', 'Qatar'), ('SA', 'Saudi Arabia'), ('SO', 'Somalia'), ('SD', 'Sudan'), ('SY', 'Syria'), ('TN', 'Tunisia'), ('AE', 'United Arab Emirates'), ('YE', 'Yemen'), ('US', 'United States'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('TR', 'Turkey'), ('OT', 'Other')], default='SA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding_vector', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice Note')], default='text', max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('voice_note_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.client')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.message')),
            ],
        ),
    ]
