# Generated by Django 5.2.6 on 2025-10-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_alter_response_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeBaseChunk',
        ),
        migrations.RemoveField(
            model_name='response',
            name='id',
        ),
        migrations.AlterField(
            model_name='response',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webhook.message'),
        ),
    ]
